// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/mengbin92/goca/internal/biz"
	"github.com/mengbin92/goca/internal/conf"
	"github.com/mengbin92/goca/internal/data"
	"github.com/mengbin92/goca/internal/service"
	"github.com/mengbin92/goca/internal/server"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	caRepo := data.NewCARepo(dataData, logger)
	caUsecase := biz.NewCAUseCase(caRepo, logger)
	caService := service.NewCertService(caUsecase,logger)
	grpcServer := server.NewGRPCServer(confServer, caService, logger)
	httpServer := server.NewHTTPServer(confServer, caService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
